---
services:
  parser:
    container_name: parser 
    image: parser
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
    restart: always
    build:
      context: .
      dockerfile: ParserGame/Dockerfile
    networks:
      - joystore
    ports:
      - "8080:8080"

networks:
  joystore:
    external: true
